/* ***********************************************
 * author :  likeyi
 * function: 
 * history:  created by likeyi 2016/7/4 16:49:58 
 * ***********************************************/
Ext.define('CisApp.model.drgsapi.report.MedicalForm', {
    extend: 'Fm.base.Model',
    fields: [
       { name: 'AId', type: 'string' },
       { name: 'LId', type: 'string' },
       { name: 'HospitalId', type: 'string' },
       { name: 'PatientId', type: 'string' },
       { name: 'AdmissionNo', type: 'string' },
       { name: 'OutBedNum', type: 'string' },
       { name: 'AdmissionDate', type: 'date' },
       { name: 'DischargeDate', type: 'date' },
       { name: 'DoctorCode', type: 'string' },
       { name: 'IsDrugAllergy', type: 'string' },
       { name: 'AllergyDrugCode', type: 'string' },
       { name: 'AllergyDrugName', type: 'string' },
       { name: 'PathologyCode', type: 'string' },
       { name: 'IsHospitalInfected', type: 'string' },
       { name: 'HospitalInfectedCode', type: 'string' },
       { name: 'BloodTypeS', type: 'string' },
       { name: 'BloodTypeE', type: 'string' },
       { name: 'LeaveHospitalType', type: 'string' },
       { name: 'ChiefComplaint', type: 'string' },
       { name: 'MedicalHistory', type: 'string' },
       { name: 'Height', type: 'string' },
       { name: 'Weight', type: 'string' },
       { name: 'Marriage', type: 'string' },
       { name: 'BearPregnancy', type: 'string' },
       { name: 'BearYie', type: 'string' },
       { name: 'AdmissionDiseaseId', type: 'string' },
       { name: 'AdmissionDiseaseName', type: 'string' },
       { name: 'DischargeDiseaseId', type: 'string' },
       { name: 'DischargeDiseaseName', type: 'string' },
       { name: 'OperId', type: 'string' },
       { name: 'OperDate', type: 'date' },
       { name: 'IsUpload', type: 'string' },
       { name: 'IsValid', type: 'string' },
       { name: 'Operator', type: 'string' },
       { name: 'OperatingDate', type: 'date' },
       { name: 'TradeNo', type: 'string' },
       { name: 'Tsblbs', type: 'string' },
       { name: 'DiagnosePosition1', type: 'string' },
       { name: 'DiagnosePosition2', type: 'string' },
       { name: 'SurgeryHistory', type: 'string' },
       { name: 'BloodTransHistory', type: 'string' },
       { name: 'DoctorName', type: 'string' },
       { name: 'IsPathologicalExamination', type: 'string' },
       { name: 'DiagnosisCode1', type: 'string' },
       { name: 'DiagnosisName1', type: 'string' },
       { name: 'DiagnosisCode2', type: 'string' },
       { name: 'DiagnosisName2', type: 'string' },
       { name: 'DiagnosisCode3', type: 'string' },
       { name: 'DiagnosisName3', type: 'string' },
       { name: 'DiagnosisCode4', type: 'string' },
       { name: 'DiagnosisName4', type: 'string' },
       { name: 'DiagnosisCode5', type: 'string' },
       { name: 'DiagnosisName5', type: 'string' },
       { name: 'DiagnosisCode6', type: 'string' },
       { name: 'DiagnosisName6', type: 'string' },
       { name: 'DiagnosisCode7', type: 'string' },
       { name: 'DiagnosisName7', type: 'string' },
       { name: 'DiagnosisCode8', type: 'string' },
       { name: 'DiagnosisName8', type: 'string' },
       { name: 'DiagnosisCode9', type: 'string' },
       { name: 'DiagnosisName9', type: 'string' },
       { name: 'DiagnosisCode10', type: 'string' },
       { name: 'DiagnosisName10', type: 'string' },
       { name: 'DiagnosisCode11', type: 'string' },
       { name: 'DiagnosisName11', type: 'string' },
       { name: 'DiagnosisCode12', type: 'string' },
       { name: 'DiagnosisName12', type: 'string' },
       { name: 'DiagnosisCode13', type: 'string' },
       { name: 'DiagnosisName13', type: 'string' },
       { name: 'DiagnosisCode14', type: 'string' },
       { name: 'DiagnosisName14', type: 'string' },
       { name: 'DiagnosisCode15', type: 'string' },
       { name: 'DiagnosisName15', type: 'string' },
       { name: 'DiagnosisCode16', type: 'string' },
       { name: 'DiagnosisName16', type: 'string' },
       { name: 'NewbornDate', type: 'date' },
       { name: 'NewbornWeight' },
       { name: 'NewbornCurrentWeight' }
    ],
    validators: {
    }
});